### PR TITLE
Use tsc command rather than direct path

### PR DESCRIPTION
**Pull request by Jameskmonger**
As you have `typescript` in your `dependencies`, you can use its `bin` commands in your `npm` scripts. This means you don't need to know the structure of the `typescript` module and how to get to `tsc` :smile:

### CODE REVIEW

**Comment by Jameskmonger** [comment]
Hi @jj09, would you like me to close this?

**Comment by jj09** [comment]
@codefoster wasn't there an issue with having only `tsc` as posintall command when deploying to Azure App Service?

**Comment by codefoster** [comment]
It's been a little while, but I think you're right, @jj09. @Jameskmonger, did you test that that works? I don't believe that worked from me to call `tsc` directly even though it seemed like it should.

**Comment by Jameskmonger** [comment]
Yes, I've got a similar setup on my Azure App service deployment.

When running an entry from the `scripts` section of `package.json`, your `node_modules/.bin` directory is added to the path, so TypeScript will be found (as long as it is listed as a dependency). The time errors occur is if you try to call the command outside of an npm script entry.

**Pull request merged**
